// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreasureHuntWebApp.Models;

namespace TreasureHuntWebApp.Migrations
{
    [DbContext(typeof(TreasureHuntWebAppContext))]
    partial class TreasureHuntWebAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TreasureHuntWebApp.Models.AskResponse", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AskDate");

                    b.Property<int>("AskType");

                    b.Property<string>("Question");

                    b.Property<string>("Response");

                    b.HasKey("ID");

                    b.ToTable("AskResponse");
                });

            modelBuilder.Entity("TreasureHuntWebApp.Models.CrossWord", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Column");

                    b.Property<string>("Letter")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<int>("Row");

                    b.HasKey("ID");

                    b.ToTable("CrossWord");
                });

            modelBuilder.Entity("TreasureHuntWebApp.Models.Dungeon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EastID");

                    b.Property<int>("ItemID");

                    b.Property<string>("Name");

                    b.Property<int>("NorthID");

                    b.Property<int>("SouthID");

                    b.Property<string>("Storyline");

                    b.Property<int>("WestID");

                    b.Property<int>("WorldID");

                    b.HasKey("ID");

                    b.ToTable("Dungeon");
                });

            modelBuilder.Entity("TreasureHuntWebApp.Models.Question", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer");

                    b.Property<int>("AnswerIndex");

                    b.Property<int>("ClueIndex");

                    b.Property<string>("Content");

                    b.Property<int>("QuestionNumber");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("TreasureHuntWebApp.Models.Scoreboard", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<long>("Score");

                    b.HasKey("ID");

                    b.ToTable("Scoreboard");
                });

            modelBuilder.Entity("TreasureHuntWebApp.Models.Winner", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HuntID");

                    b.Property<string>("Name");

                    b.Property<DateTime>("WinTime");

                    b.HasKey("ID");

                    b.ToTable("Winner");
                });
#pragma warning restore 612, 618
        }
    }
}
